### ISSUE TITLE
Maximum images per user

### ISSUE THREAD

**Issue by andyschaff** [wolffe/imagepress#10]
Can an attribute be added to cap the amount of images users can upload? Right now it seems to be infinite.

**Comment by wolffe** [comment]
Would you like this attribute to be global or per user? What would a likely scenario for this behaviour be?

**Comment by andyschaff** [comment]
I think it'd be most useful per user. The scenario I'm working on is a paid subscription site and the administrators want to limit the users/members who sign up to 20 images. Seems that it could make sense for multiple reasons. Just an idea, thanks for the consideration!

**Comment by wolffe** [comment]
This would only work in the frontend, so let's see how the flow would look like:

If the user already has 20 images and the limit is 20, then the upload page would show a notice/warning and the form would be disabled. The notice should be configurable from the backend.

There should be a *global* limit and a *per-user* limit, set in WordPress admin **Users** section.

It can be done.

**Comment by andyschaff** [comment]
Yea that sounds exactly what I was thinking. Front-end only.

**Comment by wolffe** [comment]
This is done. It will be live in the next version, 5.9.0.

**Comment by andyschaff** [comment]
Wow that is awesome. Great turn around. Thanks so much!
