### ISSUE TITLE
Couple of issues with latest update?

### ISSUE THREAD

**Issue by andyschaff** [wolffe/imagepress#24]
Hey guys,

I just updated to the latest version of the plugin in my local dev environment and started testing and found a couple of issues. I haven't tried it outside of my dev environment, but my dev environment is the same codebase and database as my staging and production.

First issue I noticed was that after updating from version 5.6 to the latest 6.2.4, the custom author URL was no longer working. I keeps reverting back to using /author/ as the slug. I tried changing the value in the settings multiple times to different values (and resaving the WP Settings->Permalinks after each update), but no luck. Are you guys having any issues here?

Also, when I edit a WP user in the default user editing screen and hit 'Update User', I get a white screen of death. The error didn't make it to my PHP error log for whatever reason, but I think it may have to do with the update(s) for image upload limits on a per-user basis?

I think it's worth testing at least. Let me know if you can replicate any of these issues. If not, I'll try again on my staging environment.

thanks!

**Comment by wolffe** [comment]
Hi Andy, I don't have that problem with the author slug, it is working for me and 3 other customers.

The second issue is related to authors, as well, so I'll ask you a few questions regarding your server spec:

1. What server software are you using? Apache or Nginx?
2. What PHP version are you using?

Are you using the wp-config.php debug constants?

Thanks!

**Comment by andyschaff** [comment]
Interesting. Yeah, not sure why it won't update with the newer code in my local environment. As soon as I swap the 5.6 plugin files back in, it works again immediately.

Anyway, my local dev is a WAMP setup.
Apache 2.2.22
PHP 5.3.13
WP is latest 4.2.2

I haven't turned on the debug constants, but I can certainly give it a try.

**Comment by wolffe** [comment]
Do you think you could update your PHP to at least 5.5?

Let me know what the debug mode tells you.

**Comment by andyschaff** [comment]
I tried uploaded the latest imagepress plugin to the staging environment of the site and am having the same issue with the custom author URL. It reverts back to /author/ as the slug.

This environment is running 5.4.42 and I don't really have control over it. It's MediaTemple's WordPress hosting. I'm pretty positive this is the same PHP version as the production site.

I can give you credentials to the staging WordPress app if you'd like to see and play around with it for yourself. I'd really like to update the plugin, but at this point will probably continue using the older version unless this author slug thing can be resolved.

Thanks in advance!

**Comment by wolffe** [comment]
Hi Andy,

I could play with it a bit, sure. I need WordPress admin access for now, and if it doesn't work, I'll need FTP access as well.

**Comment by andyschaff** [comment]
Hey Ethan,

I appreciate it. I created a user for you. Can you send me your email address I can send you the info?

**Comment by wolffe** [comment]
Thanks. Try getbutterfly@gmail.com.
